spring:
  application:
    name: zuul-proxy-service

server:
  port: 4444
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

zuul:
  prefix: /api
  routes: 

    hello:
      path: /hello/**
      service-id: hello-service
